title: SF Space
description: My personal website
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
image_path: /assets/images

plugins:
  - jekyll-latex
  - jekyll-target-blank

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
   toc_levels: 1..2
